{% set name = "freecad.python" %}
{% set version = "0.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/looooo/freecad.python/archive/{{ version }}.tar.gz
  sha256: "aa44bd1577fc4f37dde9b9aad25ae0bb4ecf3579d8811b330f09bab520b92053"

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed --verbose .

requirements:
  build:
    - jinja2
    - freecad
    - pip
  run:
    - freecad

test:
  imports:
    - freecad  # [linux and win]
  commands:
    - python -c "from freecad import app"  # [linux and win]

about:
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: import freecad from python directly
  home: https://github.com/looooo/freecad.python

extra:
  recipe-maintainers:
    - looooo
